create table if not exists public.postings (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  title text not null,
  description text not null,
  location geography not null,
  show_address boolean not null default false,
  address text not null,
  featured_image text null,
  constraint postings_pkey primary key (id),
  constraint postings_description_check check ((length(description) < 2000)),
  constraint postings_title_check check ((length(title) < 100))
) tablespace pg_default;
create index if not exists postings_geo_index on public.postings using gist (location) tablespace pg_default;