CREATE TABLE public.posting_links (
  id bigint generated by DEFAULT AS identity NOT NULL,
  url text NOT NULL,
  link_type_id bigint NOT NULL,
  posting_id bigint NOT NULL,
  created_at timestamp WITH time zone NOT NULL DEFAULT NOW(),
  CONSTRAINT posting_links_pkey PRIMARY KEY (id),
  CONSTRAINT posting_links_posting_type_unique UNIQUE (posting_id, link_type_id),
  CONSTRAINT posting_links_link_type_id_fkey FOREIGN KEY (link_type_id) REFERENCES link_types (id),
  CONSTRAINT posting_links_posting_id_fkey FOREIGN KEY (posting_id) REFERENCES postings (id) ON UPDATE CASCADE ON DELETE CASCADE
) TABLESPACE pg_default;