create table if not exists public.link_types (
  id bigint generated by default as identity not null,
  label text not null,
  icon text null,
  prefix text null,
  constraint link_types_pkey primary key (id)
) tablespace pg_default;