create table if not exists public.posting_media (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  posting_id bigint not null,
  media_type public.media_type_enum not null default 'image'::media_type_enum,
  url text not null,
  constraint posting_media_pkey primary key (id),
  constraint posting_media_posting_id_fkey foreign key (posting_id) references postings (id) on delete cascade
) tablespace pg_default;