create table public.postings (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  title text not null,
  description text not null,
  location geography not null,
  show_address boolean not null default false,
  address text not null,
  featured_image text null,
  updated_at timestamp with time zone null default now(),
  status public.posting_status not null default 'inactive'::posting_status,
  constraint postings_pkey primary key (id),
  constraint postings_description_check check ((length(description) < 2000)),
  constraint postings_title_check check ((length(title) < 100))
) tablespace pg_default;