CREATE TABLE public.posting_categories (
  id bigint generated by DEFAULT AS identity NOT NULL,
  posting_id bigint NOT NULL,
  category_id bigint NOT NULL,
  CONSTRAINT posting_categories_pkey PRIMARY KEY (id),
  CONSTRAINT posting_categories_posting_id_category_id UNIQUE (posting_id, category_id),
  CONSTRAINT posting_categories_category_id_fkey FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE,
  CONSTRAINT posting_categories_posting_id_fkey FOREIGN KEY (posting_id) REFERENCES postings (id) ON DELETE CASCADE
) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS posting_categories_category_id_index ON public.posting_categories USING btree (category_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS posting_categories_posting_category_index ON public.posting_categories USING btree (posting_id, category_id) TABLESPACE pg_default;