CREATE TABLE public.posting_media (
  id bigint generated by DEFAULT AS identity NOT NULL,
  created_at timestamp WITH time zone NOT NULL DEFAULT NOW(),
  posting_id bigint NOT NULL,
  media_type public.media_type_enum NOT NULL DEFAULT 'image'::media_type_enum,
  url text NOT NULL,
  CONSTRAINT posting_media_pkey PRIMARY KEY (id),
  CONSTRAINT posting_media_posting_id_fkey FOREIGN KEY (posting_id) REFERENCES postings (id) ON DELETE CASCADE
) TABLESPACE pg_default;