CREATE TABLE public.link_types (
    id bigint generated by DEFAULT AS identity NOT NULL,
    label text NOT NULL,
    icon text NULL,
    prefix text NULL,
    CONSTRAINT link_types_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;