create table public.media_types (
  id bigint generated by default as identity not null,
  type text not null,
  constraint media_types_pkey primary key (id),
  constraint media_types_type_key unique (type)
) tablespace pg_default;