create table if not exists public.posting_links (
  id bigint generated by default as identity not null,
  url text not null,
  link_type_id bigint not null,
  posting_id bigint not null,
  created_at timestamp with time zone not null default now(),
  constraint posting_links_pkey primary key (id),
  constraint posting_links_link_type_id_fkey foreign key (link_type_id) references link_types (id),
  constraint posting_links_posting_id_fkey foreign key (posting_id) references postings (id) on update cascade on delete cascade
) tablespace pg_default;