create table if not exists public.categories (
  id bigint generated by default as identity not null,
  label text not null,
  icon text null,
  parent_id bigint null,
  constraint categories_pkey primary key (id)
) tablespace pg_default;