create type media_type_enum as enum ('image', 'video');
create table if not exists public.posting_media (
  id bigint generated by default as identity not null,
  posting_id bigint not null,
  media_type public.media_type_enum not null default 'image'::media_type_enum,
  url text not null,
  is_featured boolean not null default false,
  created_at timestamp with time zone not null default now(),
  constraint posting_media_pkey primary key (id),
  constraint posting_media_posting_id_fkey foreign key (posting_id) references postings (id) on delete cascade
) tablespace pg_default;