create table public.posting_media (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  posting_id bigint not null,
  media_type_id bigint not null,
  is_featured boolean not null default false,
  url text not null,
  constraint posting_media_pkey primary key (id),
  constraint posting_media_media_type_id_fkey foreign key (media_type_id) references media_types (id),
  constraint posting_media_posting_id_fkey foreign key (posting_id) references postings (id) on delete cascade
) tablespace pg_default;