create table if not exists public.postings (
  id bigint generated by default as identity not null,
  title text not null,
  description text not null,
  location postgis.geography null,
  show_address boolean null default false,
  address text null,
  created_at timestamp with time zone not null default now (),
  constraint postings_pkey primary key (id),
  constraint postings_description_check check ((length (description) < 2000)),
  constraint postings_title_check check ((length (title) < 100))
) tablespace pg_default;
create index if not exists postings_geo_index on public.postings using gist (location) tablespace pg_default;